const DB_NAME="metal-cbt-v5",STORE="state",VERSION=1;
let BANK=[],SESSION=[],index=0,mode="practice",answers={},reviewMarks={},timerHandle=null,examRemain=0,questionShown={};
let state={attempts:{},wrong:{},stars:{},notes:{},schedule:{},days:{},settings:{}};
const $=id=>document.getElementById(id);
const SUBJECT_FILES=["subject1.json","subject2.json","subject3.json","subject4.json","subject5.json"];
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function loadState(){try{const db=await openDB();return await new Promise(res=>{const t=db.transaction(STORE,"readonly"),r=t.objectStore(STORE).get("main");r.onsuccess=()=>res(r.result||state);r.onerror=()=>res(state)})}catch(e){return state}}
async function saveState(){const db=await openDB();return new Promise(res=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).put(state,"main");t.oncomplete=()=>res()})}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function subjects(){return[...new Set(BANK.map(q=>q.subject))]}
function topics(s){return[...new Set(BANK.filter(q=>!s||q.subject===s).map(q=>q.topic))].sort()}
function today(){return new Date().toLocaleDateString('en-CA')}
function rec(q){return state.attempts[q.id]||{n:0,c:0,streak:0,last:0,totalMs:0}}
function mastery(q){const r=rec(q);if(!r.n)return 0;const acc=r.c/r.n,avg=r.totalMs/r.n,speed=Math.min(1,45000/Math.max(5000,avg));return Math.round((acc*.72+Math.min(1,r.streak/4)*.18+speed*.10)*100)}
function dueIds(){const t=Date.now();return Object.entries(state.schedule).filter(([id,s])=>s.due<=t).map(([id])=>+id)}
function streakDays(){let d=new Date(),n=0;for(;;){const k=d.toLocaleDateString('en-CA');if(state.days[k]){n++;d.setDate(d.getDate()-1)}else break}return n}
function updateKPIs(){const rs=Object.values(state.attempts),n=rs.reduce((a,b)=>a+b.n,0),c=rs.reduce((a,b)=>a+b.c,0);$("kBank").textContent=BANK.length.toLocaleString();$("kAttempts").textContent=n;$("kAccuracy").textContent=n?Math.round(c/n*100)+"%":"0%";$("kWrong").textContent=Object.keys(state.wrong).length;$("kDue").textContent=dueIds().length;$("kStar").textContent=Object.keys(state.stars).length;$("kStreak").textContent=streakDays()}
function fillFilters(){$("subject").innerHTML='<option value="">전체 과목</option>'+subjects().map(s=>`<option>${s}</option>`).join("");$("topic").innerHTML='<option value="">전체 세부영역</option>'+topics("").map(s=>`<option>${s}</option>`).join("");$("subject").onchange=()=>{$("topic").innerHTML='<option value="">전체 세부영역</option>'+topics($("subject").value).map(s=>`<option>${s}</option>`).join("")}}
function basePool(){let p=BANK,s=$("subject").value,t=$("topic").value,d=$("difficulty").value;if(s)p=p.filter(q=>q.subject===s);if(t)p=p.filter(q=>q.topic===t);if(d)p=p.filter(q=>q.difficulty===d);return p}
function score(q,kind){const r=rec(q);let sc=Math.random()*5;if(kind==='new')sc+=r.n===0?100:-r.n*5;if(kind==='weak')sc+=(100-mastery(q))*1.5+r.n*2;if(kind==='due')sc+=state.schedule[q.id]?.due<=Date.now()?100:0;if(kind==='wrong')sc+=state.wrong[q.id]?100:0;if(kind==='practice')sc+=r.n===0?18:Math.max(0,25-mastery(q)/4);return sc}
function diverseSelect(pool,count,kind='practice'){
  const ranked=[...pool].sort((a,b)=>score(b,kind)-score(a,kind));const out=[],deferred=[];let recentFamilies=[],recentTopics=[];
  for(const q of ranked){const fam=q.family_id||q.concept_id||q.topic;const topic=q.topic;const clash=recentFamilies.includes(fam)||recentTopics.slice(-2).includes(topic);if(clash)deferred.push(q);else{out.push(q);recentFamilies.push(fam);recentTopics.push(topic);if(recentFamilies.length>5)recentFamilies.shift();if(recentTopics.length>4)recentTopics.shift();if(out.length>=count)break}}
  if(out.length<count){for(const q of deferred){if(!out.some(x=>x.id===q.id))out.push(q);if(out.length>=count)break}}
  return out;
}
function createSession(){answers={};reviewMarks={};questionShown={};index=0;$("result").classList.remove("show");let p=basePool();const count=Number($("count").value)||50;
 if(mode==='exam'){let out=[];for(const s of subjects())out.push(...diverseSelect(BANK.filter(q=>q.subject===s),20,'practice'));SESSION=out;startTimer(150*60)}
 else{if(mode==='wrong')p=p.filter(q=>state.wrong[q.id]);if(mode==='star')p=p.filter(q=>state.stars[q.id]);if(mode==='due'){const set=new Set(dueIds());p=p.filter(q=>set.has(q.id))}if(mode==='weak')p=p.filter(q=>rec(q).n>0);if(mode==='new')p=p.filter(q=>rec(q).n===0);SESSION=diverseSelect(p,Math.min(count,p.length),mode);startTimer(0)}render()}
function startTimer(sec){if(timerHandle)clearInterval(timerHandle);examRemain=sec;const started=Date.now();const tick=()=>{let v=sec?Math.max(0,examRemain--):Math.floor((Date.now()-started)/1000);$("timer").textContent=`${String(Math.floor(v/60)).padStart(2,"0")}:${String(v%60).padStart(2,"0")}`;if(sec&&v===0){clearInterval(timerHandle);finishExam()}};tick();timerHandle=setInterval(tick,1000)}
function q(){return SESSION[index]}
function render(){const x=q();if(!x){$("qmeta").textContent="조건에 맞는 문제가 없습니다.";$("qtext").textContent="다른 학습 조건을 선택하세요.";$("choices").innerHTML="";$("palette").innerHTML="";return}if(!questionShown[x.id])questionShown[x.id]=Date.now();
 $("qmeta").innerHTML=`<span class="tag">${index+1}/${SESSION.length}</span><span class="tag">${x.subject}</span><span class="tag">${x.topic}</span><span class="tag">난이도 ${x.difficulty}</span><span class="tag">${x.type}</span><span class="tag">숙련도 ${mastery(x)}%</span><span class="tag trust">${x.trust==='verified-core'?'검증핵심':'규칙검증'}</span>`;
 $("qtext").textContent=x.question;$("choices").innerHTML="";$("explain").classList.add("hidden");x.choices.forEach((c,i)=>{const b=document.createElement("button");b.className="choice";b.textContent=`${i+1}. ${c}`;b.onclick=()=>choose(i+1);$("choices").appendChild(b)});const old=answers[x.id];if(old)showAnswer(old);$("starBtn").textContent=state.stars[x.id]?"★ 별표":"☆ 별표";$("reviewBtn").textContent=reviewMarks[x.id]?"✓ 검토 표시":"검토 표시";$("note").value=state.notes[x.id]||"";renderPalette();renderSubjectProgress()}
function showAnswer(sel){const x=q();[...$("choices").children].forEach((b,i)=>{b.disabled=true;if(i+1===x.answer)b.classList.add("correct");if(i+1===sel&&sel!==x.answer)b.classList.add("wrong")});$("explain").textContent=x.explanation+`\n\n출처/분류: ${x.source}`;$("explain").classList.remove("hidden")}
async function choose(sel){const x=q();if(answers[x.id])return;answers[x.id]=sel;const ok=sel===x.answer,r=rec(x),elapsed=Math.max(1000,Date.now()-(questionShown[x.id]||Date.now()));r.n++;if(ok){r.c++;r.streak++}else r.streak=0;r.last=Date.now();r.totalMs=(r.totalMs||0)+elapsed;state.attempts[x.id]=r;if(!ok)state.wrong[x.id]={count:(state.wrong[x.id]?.count||0)+1,last:Date.now()};else if(state.wrong[x.id]&&r.streak>=2)delete state.wrong[x.id];const ints=[1,3,7,14,30,60,120],days=ok?ints[Math.min(r.streak-1,ints.length-1)]:1;state.schedule[x.id]={due:Date.now()+days*86400000};state.days[today()]=(state.days[today()]||0)+1;await saveState();showAnswer(sel);updateKPIs();renderPalette();renderSubjectProgress()}
function renderPalette(){$("palette").innerHTML="";SESSION.forEach((x,i)=>{const b=document.createElement("button");b.textContent=i+1;b.onclick=()=>{index=i;render()};if(i===index)b.classList.add("current");if(answers[x.id])b.classList.add(answers[x.id]===x.answer?"answered":"wrong");if(reviewMarks[x.id])b.classList.add("review");$("palette").appendChild(b)})}
function renderSubjectProgress(){let h="";for(const s of subjects()){const a=SESSION.filter(x=>x.subject===s);if(!a.length)continue;const n=a.filter(x=>answers[x.id]).length,p=Math.round(n/a.length*100);h+=`<div class="progressRow">${s} ${n}/${a.length}<div class="bar"><i style="width:${p}%"></i></div></div>`}$("subjectProgress").innerHTML=h}
function finishExam(){if(mode!=="exam")return;let h="<h2>실전 모의고사 결과</h2><div class='resultGrid'>",total=0,failS=false;for(const s of subjects()){const a=SESSION.filter(x=>x.subject===s),c=a.filter(x=>answers[x.id]===x.answer).length,sc=Math.round(c/a.length*100);total+=c;if(sc<40)failS=true;h+=`<div class='resultBox'>${s}<br><b>${sc}점</b><br>${c}/${a.length}</div>`}const avg=Math.round(total/SESSION.length*100),pass=avg>=60&&!failS;h+=`</div><h2 class="${pass?'pass':'fail'}">${pass?'합격':'불합격'} · 평균 ${avg}점</h2><p>${failS?'과목별 40점 미만 과락이 있습니다.':avg<60?'평균 60점 미만입니다.':'평균 60점 이상, 과락 없음.'}</p>`;$("result").innerHTML=h;$("result").classList.add("show");$("result").scrollIntoView({behavior:"smooth"})}
$("prevBtn").onclick=()=>{if(index>0){index--;render()}};$("nextBtn").onclick=()=>{if(index<SESSION.length-1){index++;render()}else if(mode==='exam')finishExam()};$("reviewBtn").onclick=()=>{const x=q();if(x){reviewMarks[x.id]=!reviewMarks[x.id];render()}};$("starBtn").onclick=async()=>{const x=q();if(!x)return;if(state.stars[x.id])delete state.stars[x.id];else state.stars[x.id]=1;await saveState();updateKPIs();render()};$("note").onchange=async()=>{const x=q();if(!x)return;const v=$("note").value.trim();if(v)state.notes[x.id]=v;else delete state.notes[x.id];await saveState()};
document.querySelectorAll(".modebar button").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".modebar button").forEach(x=>x.classList.toggle("active",x===b))});$("startBtn").onclick=createSession;$("closeInstall").onclick=()=>$("installTip").classList.add("hidden");
async function boot(){state=await loadState();try{const man=await fetch("data/manifest.json").then(r=>r.json());const chunks=await Promise.all(SUBJECT_FILES.map(f=>fetch("data/"+f).then(r=>{if(!r.ok)throw new Error(f+" "+r.status);return r.json()})));BANK=chunks.flat();$("bankLabel").textContent=`실저장 독립문항 ${BANK.length.toLocaleString()}개 · 문구 셔플 가상문항 제거 · ${Object.keys(man.subjects).length}과목`;fillFilters();updateKPIs();$("qmeta").textContent="문제은행 준비 완료";$("qtext").textContent=`독립 지문 ${BANK.length.toLocaleString()}개를 불러왔습니다. 과목별 학습 또는 신규 우선 모드를 선택하세요.`}catch(e){$("qmeta").textContent="문제은행 로드 실패";$("qtext").textContent="data 파일을 읽지 못했습니다: "+e.message;console.error(e)}if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js")}
boot();
