const DB_NAME="metal-cbt-v4",STORE="state",VERSION=1;let CORE=[],SESSION=[],index=0,mode="practice",answers={},reviewMarks={},started=0,timerHandle=null,examRemain=0;let state={attempts:{},wrong:{},stars:{},notes:{},schedule:{},days:{},settings:{}};
const $=id=>document.getElementById(id);
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function loadState(){try{const db=await openDB();return await new Promise(res=>{const t=db.transaction(STORE,"readonly"),r=t.objectStore(STORE).get("main");r.onsuccess=()=>res(r.result||state);r.onerror=()=>res(state)})}catch(e){return state}}
async function saveState(){const db=await openDB();return new Promise(res=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).put(state,"main");t.oncomplete=()=>res()})}
function shuffle(a,rng=Math.random){for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function xorshift(seed){let x=seed|0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)%1000000)/1000000}}
function variantOf(q,v){if(v===0)return{...q,vid:`${q.id}-0`,variant:0};const p=["","[개념 확인] ","[기사형 판단] ","[핵심 복습] ","[유형 변형] ","[실전 대비] "],s=[""," 가장 적절한 답을 고르시오."," 옳은 선택지를 고르시오."," 기사시험 기준으로 판단하시오."," 다음 중 맞는 것을 고르시오."];const rng=xorshift(q.id*1009+v*9176),pairs=q.choices.map((c,i)=>({c,i:i+1}));shuffle(pairs,rng);return{...q,vid:`${q.id}-${v}`,variant:v,question:p[v%p.length]+q.question+s[(v*3)%s.length],choices:pairs.map(x=>x.c),answer:pairs.findIndex(x=>x.i===q.answer)+1}}
function subjects(){return[...new Set(CORE.map(q=>q.subject))]} function topics(s){return[...new Set(CORE.filter(q=>!s||q.subject===s).map(q=>q.topic))].sort()}
function today(){return new Date().toISOString().slice(0,10)} function now(){return Date.now()} function rec(q){return state.attempts[q.id]||{n:0,c:0,streak:0,last:0,totalMs:0}}
function mastery(q){const r=rec(q);if(!r.n)return 0;const acc=r.c/r.n,speed=r.totalMs?Math.min(1,45000/(r.totalMs/r.n)):0.5;return Math.round((acc*.7+Math.min(1,r.streak/4)*.2+speed*.1)*100)}
function dueIds(){const t=Date.now();return Object.entries(state.schedule).filter(([id,s])=>s.due<=t).map(([id])=>+id)} function streakDays(){let d=new Date(),n=0;for(;;){const k=d.toISOString().slice(0,10);if(state.days[k]){n++;d.setDate(d.getDate()-1)}else break}return n}
function updateKPIs(){const rs=Object.values(state.attempts),n=rs.reduce((a,b)=>a+b.n,0),c=rs.reduce((a,b)=>a+b.c,0);$("kAttempts").textContent=n;$("kAccuracy").textContent=n?Math.round(c/n*100)+"%":"0%";$("kWrong").textContent=Object.keys(state.wrong).length;$("kDue").textContent=dueIds().length;$("kStar").textContent=Object.keys(state.stars).length;$("kStreak").textContent=streakDays()}
function fillFilters(){$("subject").innerHTML='<option value="">전체 과목</option>'+subjects().map(s=>`<option>${s}</option>`).join("");$("topic").innerHTML='<option value="">전체 세부영역</option>'+topics("").map(s=>`<option>${s}</option>`).join("");$("subject").onchange=()=>{$("topic").innerHTML='<option value="">전체 세부영역</option>'+topics($("subject").value).map(s=>`<option>${s}</option>`).join("")}}
function basePool(){let p=CORE,s=$("subject").value,t=$("topic").value,d=$("difficulty").value;if(s)p=p.filter(q=>q.subject===s);if(t)p=p.filter(q=>q.topic===t);if(d)p=p.filter(q=>q.difficulty===d);return p}
function uniqueVariants(base,count){const out=[];for(const q of shuffle([...base])){out.push(variantOf(q,Math.floor(Math.random()*25)));if(out.length>=count)break}return out}
function weakPool(){return CORE.filter(q=>rec(q).n>0).sort((a,b)=>mastery(a)-mastery(b)).slice(0,150)}
function createSession(){answers={};reviewMarks={};index=0;$("result").classList.remove("show");if(mode==="exam"){let out=[];for(const s of subjects())out.push(...uniqueVariants(CORE.filter(q=>q.subject===s),20));SESSION=out;startTimer(150*60)}else{let b=basePool();if(mode==="wrong")b=b.filter(q=>state.wrong[q.id]);if(mode==="star")b=b.filter(q=>state.stars[q.id]);if(mode==="due"){const set=new Set(dueIds());b=b.filter(q=>set.has(q.id))}if(mode==="weak")b=weakPool();SESSION=uniqueVariants(b,Math.min(100,b.length));startTimer(0)}render()}
function startTimer(sec){if(timerHandle)clearInterval(timerHandle);started=Date.now();examRemain=sec;const tick=()=>{let v=sec?Math.max(0,examRemain--):Math.floor((Date.now()-started)/1000);$("timer").textContent=`${String(Math.floor(v/60)).padStart(2,"0")}:${String(v%60).padStart(2,"0")}`;if(sec&&v===0){clearInterval(timerHandle);finishExam()}};tick();timerHandle=setInterval(tick,1000)}
function q(){return SESSION[index]} function render(){const x=q();if(!x){$("qmeta").textContent="조건에 맞는 문제가 없습니다.";$("qtext").textContent="다른 학습 조건을 선택하세요.";$("choices").innerHTML="";$("palette").innerHTML="";return}$("qmeta").innerHTML=`<span>${index+1}/${SESSION.length}</span><span>${x.subject}</span><span>${x.topic}</span><span>난이도 ${x.difficulty}</span><span>숙련도 ${mastery(x)}%</span>${x.variant?`<span>파생 ${x.variant}</span>`:"<span>핵심</span>"}`;$("qtext").textContent=x.question;$("choices").innerHTML="";$("explain").classList.add("hidden");x.choices.forEach((c,i)=>{const b=document.createElement("button");b.className="choice";b.textContent=`${i+1}. ${c}`;b.onclick=()=>choose(i+1);$("choices").appendChild(b)});const old=answers[x.vid];if(old)showAnswer(old);$("starBtn").textContent=state.stars[x.id]?"★ 별표":"☆ 별표";$("reviewBtn").textContent=reviewMarks[x.vid]?"✓ 검토 표시":"검토 표시";$("note").value=state.notes[x.id]||"";renderPalette();renderSubjectProgress()}
function showAnswer(sel){const x=q();[...$("choices").children].forEach((b,i)=>{b.disabled=true;if(i+1===x.answer)b.classList.add("correct");if(i+1===sel&&sel!==x.answer)b.classList.add("wrong")});$("explain").textContent=x.explanation;$("explain").classList.remove("hidden")}
async function choose(sel){const x=q();if(answers[x.vid])return;answers[x.vid]=sel;const ok=sel===x.answer,r=rec(x);r.n++;if(ok){r.c++;r.streak++}else r.streak=0;r.last=now();r.totalMs=(r.totalMs||0)+Math.max(1000,Date.now()-started);state.attempts[x.id]=r;if(!ok)state.wrong[x.id]={count:(state.wrong[x.id]?.count||0)+1,last:now()};else if(state.wrong[x.id]&&r.streak>=2)delete state.wrong[x.id];const ints=[1,3,7,14,30,60,120],days=ok?ints[Math.min(r.streak-1,ints.length-1)]:1;state.schedule[x.id]={due:Date.now()+days*86400000};state.days[today()]=(state.days[today()]||0)+1;await saveState();showAnswer(sel);updateKPIs();renderPalette();renderSubjectProgress()}
function renderPalette(){$("palette").innerHTML="";SESSION.forEach((x,i)=>{const b=document.createElement("button");b.textContent=i+1;b.onclick=()=>{index=i;render()};if(i===index)b.classList.add("current");if(answers[x.vid])b.classList.add(answers[x.vid]===x.answer?"answered":"wrong");if(reviewMarks[x.vid])b.classList.add("review");$("palette").appendChild(b)})}
function renderSubjectProgress(){let h="";for(const s of subjects()){const a=SESSION.filter(x=>x.subject===s);if(!a.length)continue;const n=a.filter(x=>answers[x.vid]).length,p=Math.round(n/a.length*100);h+=`<div class="progressRow">${s} ${n}/${a.length}<div class="bar"><i style="width:${p}%"></i></div></div>`}$("subjectProgress").innerHTML=h}
function finishExam(){if(mode!=="exam")return;let h="<h2>실전 모의고사 결과</h2><div class='resultGrid'>",total=0,failS=false;for(const s of subjects()){const a=SESSION.filter(x=>x.subject===s),c=a.filter(x=>answers[x.vid]===x.answer).length,sc=Math.round(c/a.length*100);total+=c;if(sc<40)failS=true;h+=`<div class='resultBox'>${s}<br><b>${sc}점</b><br>${c}/${a.length}</div>`}const avg=Math.round(total/SESSION.length*100),pass=avg>=60&&!failS;h+=`</div><h2 class="${pass?"pass":"fail"}">${pass?"합격":"불합격"} · 평균 ${avg}점</h2>`;$("result").innerHTML=h;$("result").classList.add("show");$("result").scrollIntoView({behavior:"smooth"})}
$("prevBtn").onclick=()=>{if(index>0){index--;render()}};$("nextBtn").onclick=()=>{if(index<SESSION.length-1){index++;render()}else if(mode==="exam")finishExam()};$("reviewBtn").onclick=()=>{const x=q();if(x){reviewMarks[x.vid]=!reviewMarks[x.vid];render()}};$("starBtn").onclick=async()=>{const x=q();if(!x)return;if(state.stars[x.id])delete state.stars[x.id];else state.stars[x.id]=1;await saveState();updateKPIs();render()};$("note").onchange=async()=>{const x=q();if(!x)return;const v=$("note").value.trim();if(v)state.notes[x.id]=v;else delete state.notes[x.id];await saveState()};
document.querySelectorAll(".modebar button").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".modebar button").forEach(x=>x.classList.toggle("active",x===b))});$("startBtn").onclick=createSession;$("closeInstall").onclick=()=>$("installTip").classList.add("hidden");
async function boot(){state=await loadState();CORE=await fetch("data/questions.json").then(r=>r.json());fillFilters();updateKPIs();$("qmeta").textContent="문제은행 준비 완료";$("qtext").textContent=`검증 핵심 ${CORE.length.toLocaleString()}문제 × 25변형 = 가상 50,000문제. 학습 모드를 선택하세요.`;if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js")}boot();